name: CI/CD Pipeline

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main  # Change to your default branch, e.g., 'main' or 'master'
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main'

# Define the CI/CD jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version here

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional but recommended)
      - name: Run tests
        run: npm run test

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Deploy to your environment (Vercel, AWS, or another platform)
      - name: Deploy to Vercel (or another platform)
        if: github.ref == 'refs/heads/main'  # Only deploy on push to main branch
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
          
  # Optionally, you can create another job for testing deployment status
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Check the status of the deployed app (this example uses cURL)
      - name: Check deployment status
        run: |
          curl -f https://<your-vercel-app-url> || exit 1
